// state.js - TaskMind 状態管理

const state = {
    mode: 'select',
    nodes: [],
    connections: [],
    groups: [],
    nextId: 1,
    scale: 1,
    panX: 0,
    panY: 0,
    isPanning: false,
    lastMouseX: 0,
    lastMouseY: 0,
    rightClickPanning: false,
    rightClickPanStartX: 0,
    rightClickPanStartY: 0,
    suppressContextMenu: false,
    selectedNodeId: null,
    selectedNodeIds: [],
    isSelecting: false,
    selectionStartX: 0,
    selectionStartY: 0,
    connectingFrom: null,
    pendingConnectionType: null,
    pendingConnectionCustomType: null,
    dragNode: null,
    dragOffsetX: 0,
    dragOffsetY: 0,
    lastPinchDist: 0,
    lastPinchScale: 1,
    draggingConn: null,
    connDragTarget: null,
    pendingConnectionFrom: null,
    resizingNode: null,
    resizeStartX: 0,
    resizeStartY: 0,
    resizeStartWidth: 0,
    resizeStartHeight: 0,
    colors: DEFAULT_COLORS,
    reorderTarget: null,
    lastFileHandle: null,
    lastFileName: null,
    hideCompleted: false,
    layoutMode: LAYOUT_MODES.FREE,
    timeline: {
        viewStart: new Date().toISOString().split('T')[0],
        viewRange: TIMELINE_DEFAULTS.viewRange,
        dayWidth: TIMELINE_DEFAULTS.dayWidth,
        laneHeight: TIMELINE_DEFAULTS.laneHeight,
        expandedLanes: { ...TIMELINE_DEFAULTS.expandedLanes }
    },
    customConnectionTypes: [...DEFAULT_CONNECTION_TYPES]
};
